import { StatusBarStyle } from "expo-status-bar";

export const defaultTheme = {
  mode: "default",
  STATUS_BAR_STYLE: "light" as StatusBarStyle,

  PRIMARY_BACKGROUND_COLOR: "#15202B",
  PRIMARY_TEXT_COLOR: "#FFFFFF",
  SECONDARY_BACKGROUND_COLOR: "#d116d8",
  SECONDARY_TEXT_COLOR: "#d116d8",

  MUTED_TEXT_COLOR: "#4B7299",
  BODY_TEXT_COLOR: "#A1B9D1",

  PRIMARY_BUTTON_TEXT_COLOR: "#FFFFFF",
  SECONDARY_BUTTON_TEXT_COLOR: "#d116d8",

  PRIMARY_BUTTON_BACKGROUND_COLOR: "#d116d8",
  SECONDARY_BUTTON_BACKGROUND_COLOR: "#FFFFFF",

  PRIMARY_BUTTON_ANDROID_RIPPLE_BACKGROUND_COLOR: "#d116d8",
  SECONDARY_BUTTON_ANDROID_RIPPLE_BACKGROUND_COLOR: "#dfdfdf",

  FORM_BACKGROUND_COLOR: "#223446",
  INPUT_PLACEHOLDER_TEXT_COLOR: "#304962",

  FACEBOOK_BACKGROUND_COLOR: "#0078FF",
  GOOGLE_BACKGROUND_COLOR: "#FFFFFF",
  GOOGLE_TEXT_COLOR: "#15202B",
  GOOGLE_ICON_COLOR: "#DB4437",

  SEPARATOR_COLOR: "#223446",
  SEPARATOR_TEXT_COLOR: "#57585B",

  DANGER_COLOR: "#fd485a",
  SUCCESS_COLOR: "#4BB543",
  WARNING_COLOR: "#FFA500",
};
